// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { AssessmentsQuickAssessmentData, AssessmentsQuickAssessmentResponse, AssessmentsCreateAndPersistAssessmentData, AssessmentsCreateAndPersistAssessmentResponse, AssessmentsListUserAssessmentsData, AssessmentsListUserAssessmentsResponse, AssessmentsGetGeodataData, AssessmentsGetGeodataResponse, AssessmentsGetAssessmentDetailData, AssessmentsGetAssessmentDetailResponse, LoginLoginAccessTokenData, LoginLoginAccessTokenResponse, LoginTestTokenResponse, LoginRecoverPasswordData, LoginRecoverPasswordResponse, LoginResetPasswordData, LoginResetPasswordResponse, LoginRecoverPasswordHtmlContentData, LoginRecoverPasswordHtmlContentResponse, PrivateCreateUserData, PrivateCreateUserResponse, SettingsGetApiKeyStatusResponse, SettingsUpdateApiKeysData, SettingsUpdateApiKeysResponse, UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersReadUserMeResponse, UsersDeleteUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse, UsersRegisterUserData, UsersRegisterUserResponse, UsersReadUserByIdData, UsersReadUserByIdResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse, UtilsTestEmailData, UtilsTestEmailResponse, UtilsHealthCheckResponse, UtilsPurgeCacheResponse, VehiclesListVehiclesResponse, VehiclesGetVehicleData, VehiclesGetVehicleResponse } from './types.gen';

export class AssessmentsService {
    /**
     * Quick Assessment
     * Full access assessment for a UK postcode.
     * Returns Green/Amber/Red rating per vehicle class with GeoJSON overlays.
     * @param data The data for the request.
     * @param data.postcode UK postcode e.g. BN1 1AB
     * @param data.vehicleClasses Filter by vehicle class names
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static quickAssessment(data: AssessmentsQuickAssessmentData): CancelablePromise<AssessmentsQuickAssessmentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/assessments/quick',
            query: {
                postcode: data.postcode,
                vehicle_classes: data.vehicleClasses
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create And Persist Assessment
     * Run a full assessment and persist the results for the authenticated user.
     * @param data The data for the request.
     * @param data.postcode UK postcode e.g. BN1 1AB
     * @param data.vehicleClasses Filter by vehicle class names
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static createAndPersistAssessment(data: AssessmentsCreateAndPersistAssessmentData): CancelablePromise<AssessmentsCreateAndPersistAssessmentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/assessments/',
            query: {
                postcode: data.postcode,
                vehicle_classes: data.vehicleClasses
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * List User Assessments
     * List past assessments for the current user.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static listUserAssessments(data: AssessmentsListUserAssessmentsData = {}): CancelablePromise<AssessmentsListUserAssessmentsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/assessments/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Geodata
     * Returns raw OS MasterMap GeoJSON around a postcode.
     * For debugging and verifying the OS API integration.
     * @param data The data for the request.
     * @param data.postcode
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static getGeodata(data: AssessmentsGetGeodataData): CancelablePromise<AssessmentsGetGeodataResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/assessments/geodata/{postcode}',
            path: {
                postcode: data.postcode
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Assessment Detail
     * Get a specific assessment by ID.
     * @param data The data for the request.
     * @param data.assessmentId
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static getAssessmentDetail(data: AssessmentsGetAssessmentDetailData): CancelablePromise<AssessmentsGetAssessmentDetailResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/assessments/{assessment_id}',
            path: {
                assessment_id: data.assessmentId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class LoginService {
    /**
     * Login Access Token
     * OAuth2 compatible token login, get an access token for future requests
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginAccessToken(data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Test Token
     * Test access token
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static testToken(): CancelablePromise<LoginTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/test-token'
        });
    }
    
    /**
     * Recover Password
     * Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static recoverPassword(data: LoginRecoverPasswordData): CancelablePromise<LoginRecoverPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Reset Password
     * Reset password
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static resetPassword(data: LoginResetPasswordData): CancelablePromise<LoginResetPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/reset-password/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Recover Password Html Content
     * HTML Content for Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns string Successful Response
     * @throws ApiError
     */
    public static recoverPasswordHtmlContent(data: LoginRecoverPasswordHtmlContentData): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery-html-content/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PrivateService {
    /**
     * Create User
     * Create a new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: PrivateCreateUserData): CancelablePromise<PrivateCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class SettingsService {
    /**
     * Get Api Key Status
     * Get the current status of configured API keys.
     * Keys are masked for security — only first/last 4 chars shown.
     * @returns ApiKeyStatus Successful Response
     * @throws ApiError
     */
    public static getApiKeyStatus(): CancelablePromise<SettingsGetApiKeyStatusResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/settings/api-keys'
        });
    }
    
    /**
     * Update Api Keys
     * Update API keys at runtime. Only non-null fields are updated.
     * Changes persist in memory for the current server process.
     * To persist across restarts, also update the .env file.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ApiKeyStatus Successful Response
     * @throws ApiError
     */
    public static updateApiKeys(data: SettingsUpdateApiKeysData): CancelablePromise<SettingsUpdateApiKeysResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/settings/api-keys',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UsersService {
    /**
     * Read Users
     * Retrieve users.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create User
     * Create new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Me
     * Get current user.
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Delete User Me
     * Delete own user.
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Update User Me
     * Update own user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Password Me
     * Update own password.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updatePasswordMe(data: UsersUpdatePasswordMeData): CancelablePromise<UsersUpdatePasswordMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Register User
     * Create new user without the need to be logged in.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static registerUser(data: UsersRegisterUserData): CancelablePromise<UsersRegisterUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User By Id
     * Get a specific user by id.
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserById(data: UsersReadUserByIdData): CancelablePromise<UsersReadUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User
     * Update a user.
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User
     * Delete a user.
     * @param data The data for the request.
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Test Email
     * Test emails.
     * @param data The data for the request.
     * @param data.emailTo
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email/',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Health Check
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
    
    /**
     * Purge Cache
     * Purge all expired geo-cache entries (admin only).
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static purgeCache(): CancelablePromise<UtilsPurgeCacheResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/purge-cache/'
        });
    }
}

export class VehiclesService {
    /**
     * List Vehicles
     * List all vehicle profiles.
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static listVehicles(): CancelablePromise<VehiclesListVehiclesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/vehicles/'
        });
    }
    
    /**
     * Get Vehicle
     * Get a single vehicle profile by class name.
     * @param data The data for the request.
     * @param data.vehicleClass
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static getVehicle(data: VehiclesGetVehicleData): CancelablePromise<VehiclesGetVehicleResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/vehicles/{vehicle_class}',
            path: {
                vehicle_class: data.vehicleClass
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}